# Generated by Django 6.0.1 on 2026-01-21 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('ingredients', models.TextField()),
                ('instructions', models.TextField()),
                ('image_url', models.URLField(blank=True, null=True)),
                ('diet', models.CharField(blank=True, max_length=50, null=True)),
                ('gluten_free', models.BooleanField(default=False)),
                ('vegan', models.BooleanField(default=False)),
                ('vegetarian', models.BooleanField(default=False)),
                ('ready_in_minutes', models.IntegerField(default=0)),
                ('servings', models.IntegerField(default=1)),
                ('likes', models.IntegerField(default=0)),
            ],
        ),
    ]
